name: vacation-system
services:
  postgres:
    container_name: postgres-vacation-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: vacation_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: always

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local